"""Prompt builders for the decoupled tags steps."""

from src.entities.tags_gpt.prompts.prompts import (
    CLAIM_CLUSTER_RULES,
    CLAIM_EXTRACTION_RULES,
    STANCE_FORMAT_RULES,
    STANCE_RUBRIC,
    STANCE_TYPE_GUIDES,
    STANCE_TYPE_TIE_BREAK,
    bootstrap_prompt,
    claim_catalog_block,
    claim_tagging_prompt,
    claim_update_prompt,
    consistency_pass_prompt,
    customer_block,
    event_block,
    indexed_block,
    items_block,
    stance_catalog_block,
    stance_tagging_prompt,
    stance_type_guide,
    stance_update_prompt,
    type_triage_prompt,
)

__all__ = [
    "CLAIM_CLUSTER_RULES",
    "CLAIM_EXTRACTION_RULES",
    "STANCE_FORMAT_RULES",
    "STANCE_RUBRIC",
    "STANCE_TYPE_GUIDES",
    "STANCE_TYPE_TIE_BREAK",
    "bootstrap_prompt",
    "claim_catalog_block",
    "claim_tagging_prompt",
    "claim_update_prompt",
    "consistency_pass_prompt",
    "customer_block",
    "event_block",
    "indexed_block",
    "items_block",
    "stance_catalog_block",
    "stance_tagging_prompt",
    "stance_type_guide",
    "stance_update_prompt",
    "type_triage_prompt",
]
